-- Bremen roster seed from the historical member sheet.
--
-- Session/instrument stays separate from position. Emails are intentionally
-- null for roster-only rows and are filled when a member claims the row.

update public.members
set student_year = 2021,
    instrument = '보컬',
    approved_at = coalesce(approved_at, now()),
    updated_at = now()
where lower(email) = lower('hyeongsoo@postech.ac.kr')
  and name = '김형수';

with roster(student_year, name, instrument, position, current_status, status) as (
  values
    (2012, '채수강', '보컬', null, null, 'alumni'),
    (2012, '김경준', '기타', null, null, 'alumni'),
    (2012, '이은호', '베이스', null, null, 'alumni'),
    (2012, '김도균', '드럼', null, null, 'alumni'),
    (2013, '배윤아', '보컬', null, null, 'alumni'),
    (2013, '송현섭', '키보드', null, null, 'alumni'),
    (2013, '유정민', '기타', null, null, 'alumni'),
    (2014, '권원표', '베이스', null, null, 'alumni'),
    (2014, '변준석', '기타', null, null, 'alumni'),
    (2014, '김은아', '베이스', null, null, 'alumni'),
    (2014, '이용우', '드럼', null, null, 'alumni'),
    (2014, '노효균', '드럼', null, null, 'alumni'),
    (2014, '이승희', '기타', null, null, 'alumni'),
    (2014, '이훈원', '드럼', null, null, 'alumni'),
    (2014, '김민경', '베이스', null, null, 'alumni'),
    (2014, '안태훈', '보컬', null, null, 'alumni'),
    (2015, '김성태', '기타', null, null, 'alumni'),
    (2015, '김지성', '보컬', null, null, 'alumni'),
    (2015, '박종민', '기타', null, null, 'alumni'),
    (2015, '신주희', '키보드', null, null, 'alumni'),
    (2015, '오현명', '베이스', null, null, 'alumni'),
    (2015, '유위범', '보컬', null, null, 'alumni'),
    (2015, '이지연', '드럼', null, null, 'alumni'),
    (2016, '김준희', '보컬', null, null, 'alumni'),
    (2016, '문건호', '기타', null, null, 'alumni'),
    (2016, '성재현', '드럼', null, null, 'alumni'),
    (2016, '이동건', '보컬', null, null, 'alumni'),
    (2016, '전길수', '베이스', null, null, 'alumni'),
    (2016, '전하은', '키보드', null, null, 'alumni'),
    (2016, '채상윤', '드럼', null, null, 'alumni'),
    (2016, '홍승하', '기타', null, null, 'alumni'),
    (2016, '남경민', '키보드', null, null, 'alumni'),
    (2016, '김경준', '베이스', null, null, 'alumni'),
    (2017, '박문열', '베이스', null, null, 'alumni'),
    (2017, '손주은', '기타', null, null, 'alumni'),
    (2017, '이효인', '보컬', null, null, 'alumni'),
    (2017, '홍재영', '드럼', null, null, 'alumni'),
    (2017, '김태리', '보컬', null, null, 'inactive'),
    (2017, '최지훈', '기타', null, null, 'alumni'),
    (2017, '함현식', '보컬', null, null, 'alumni'),
    (2018, '김세린', '드럼', null, null, 'alumni'),
    (2018, '최은수', '베이스', '2019 회장', null, 'alumni'),
    (2018, '손희준', '기타', null, null, 'alumni'),
    (2018, '조현석', '키보드', null, null, 'alumni'),
    (2018, '류동헌', '보컬', null, null, 'alumni'),
    (2018, '전제민', '기타', null, null, 'alumni'),
    (2018, '이용남', '기타', null, null, 'alumni'),
    (2018, '김남영', '기타', null, null, 'alumni'),
    (2018, '김주희', '드럼', null, null, 'alumni'),
    (2019, '최희원', '보컬, 기타', '2020 회장', null, 'alumni'),
    (2019, '류다현', '드럼', null, null, 'alumni'),
    (2019, '김경준', '베이스', null, null, 'alumni'),
    (2019, '이정우', '드럼', null, null, 'alumni'),
    (2019, '이동하', '키보드', null, null, 'alumni'),
    (2019, '장준', '기타', null, null, 'alumni'),
    (2019, '김선우', '기타', null, null, 'alumni'),
    (2020, '이태지', '기타', '2021 회장', null, 'alumni'),
    (2020, '이신우', '키보드', null, null, 'alumni'),
    (2020, '권대영', '보컬', null, null, 'alumni'),
    (2020, '최재현', '기타', '2021 총무', '대학원(서울대)', 'alumni'),
    (2020, '류재홍', '드럼', null, '곱창, 도굴의 드럼', 'alumni'),
    (2020, '김민규', '보컬', null, null, 'alumni'),
    (2021, '김하겸', '키보드', '2022 회장', null, 'alumni'),
    (2021, '한경찬', '키보드', null, null, 'alumni'),
    (2021, '김우진', '보컬', '2022 총무', null, 'alumni'),
    (2021, '고명진', '기타', null, null, 'alumni'),
    (2021, '김영철', '기타', null, null, 'alumni'),
    (2021, '조민석', '기타', null, null, 'alumni'),
    (2021, '오종석', '드럼', null, null, 'alumni'),
    (2021, '김이헌', '베이스', null, null, 'alumni'),
    (2021, '오하윤', '베이스', null, null, 'alumni'),
    (2021, '김현우', '보컬', null, null, 'alumni'),
    (2021, '김형수', '보컬', null, null, 'active'),
    (2021, '유혜인', '보컬', null, null, 'alumni'),
    (2021, '이유민', '보컬', null, null, 'alumni'),
    (2021, '장영인', '기타', null, null, 'alumni'),
    (2021, '곽민준', '기타', null, null, 'alumni'),
    (2021, '이예지', '기타', null, null, 'alumni'),
    (2022, '안홍상', '기타', '2023 회장', null, 'active'),
    (2022, '김찬우', '기타', null, null, 'active'),
    (2022, '배준희', '기타', '2023 총무', null, 'active'),
    (2022, '백승현', '기타', null, null, 'active'),
    (2022, '홍지우', '키보드', null, null, 'active'),
    (2022, '정재희', '키보드', null, null, 'active'),
    (2022, '강인혁', '베이스', null, null, 'active'),
    (2022, '장서연', '베이스', null, null, 'active'),
    (2022, '박준혁', '드럼', null, null, 'active'),
    (2022, '백지은', '드럼', null, null, 'active'),
    (2022, '노건우', '보컬', null, null, 'active'),
    (2022, '류나은', '보컬', null, null, 'active'),
    (2022, '박준기', '보컬', null, null, 'active'),
    (2022, '변우열', '보컬', null, null, 'active'),
    (2022, '이한', '보컬', null, null, 'active'),
    (2022, '김윤서', '보컬', null, null, 'active'),
    (2023, '서환', '보컬', null, null, 'active'),
    (2023, '신성훈', '보컬', null, null, 'active'),
    (2023, '정예지', '보컬', null, null, 'active'),
    (2023, '조연정', '보컬', null, null, 'active'),
    (2023, '김효성', '기타', null, null, 'active'),
    (2023, '김동은', '기타', null, null, 'active'),
    (2023, '박민규', '기타', null, null, 'active'),
    (2023, '박성주', '기타', '2024 회장', null, 'active'),
    (2023, '이지아', '베이스', null, null, 'active'),
    (2023, '권이준', '베이스', null, null, 'active'),
    (2023, '최해민', '키보드', '2024 부회장', null, 'active'),
    (2023, '김성겸', '키보드', null, null, 'active'),
    (2023, '정지성', '드럼', null, null, 'active'),
    (2023, '김준성', '드럼', null, null, 'active'),
    (2023, '유규열', '보컬', null, null, 'active'),
    (2024, '박건호', '보컬', null, null, 'active'),
    (2024, '정서영', '보컬', '2025 회장', null, 'active'),
    (2024, '이현서', '보컬', null, null, 'active'),
    (2024, '김신빈', '기타', '2025 부회장', null, 'active'),
    (2024, '김경철', '기타', null, null, 'active'),
    (2024, '양지윤', '기타', null, null, 'active'),
    (2024, '안동현', '기타', null, null, 'active'),
    (2024, '김성은', '베이스', null, null, 'active'),
    (2024, '김영재', '베이스', null, null, 'active'),
    (2024, '신예원', '키보드', null, null, 'active'),
    (2024, '서현진', '키보드', null, null, 'active'),
    (2024, '서준희', '드럼', '2025 총무', null, 'active'),
    (2024, '이다현', '드럼', null, null, 'active'),
    (2025, '강승호', '보컬', null, null, 'active'),
    (2025, '박성현', '보컬', null, null, 'active'),
    (2025, '박윤서', '보컬', null, null, 'active'),
    (2025, '박서연', '보컬', null, null, 'active'),
    (2025, '김예성', '기타', null, null, 'active'),
    (2025, '김동규', '기타', null, null, 'active'),
    (2025, '홍이준', '기타', null, null, 'active'),
    (2025, '이형민', '기타', null, null, 'active'),
    (2025, '남궁성주', '베이스', null, null, 'active'),
    (2025, '홍준우', '베이스', null, null, 'active'),
    (2025, '채민경', '키보드', null, null, 'active'),
    (2025, '문준호', '키보드', null, null, 'active'),
    (2025, '김나령', '드럼', null, null, 'active'),
    (2025, '황준혁', '드럼', null, null, 'active')
)
insert into public.members (
  email,
  name,
  student_year,
  instrument,
  position,
  current_status,
  status,
  role,
  approved_at
)
select
  null,
  name,
  student_year,
  instrument,
  position,
  current_status,
  status::public.member_status,
  'member'::public.member_role,
  now()
from roster
on conflict (student_year, name) where student_year is not null
do update
set instrument = excluded.instrument,
    position = excluded.position,
    current_status = excluded.current_status,
    status = case
      when public.members.role = 'admin' then public.members.status
      else excluded.status
    end,
    email = case
      when public.members.role = 'admin' or public.members.auth_user_id is not null
        then public.members.email
      else null
    end,
    approved_at = coalesce(public.members.approved_at, now()),
    updated_at = now();
