// Auto-generated by Supabase MCP — do not edit by hand.
// Regenerate after schema changes:
//   pnpm dlx supabase gen types typescript --project-id tyosnoncxaewrjlbnytg > lib/supabase/types.ts
// (or via Supabase MCP `generate_typescript_types`).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      cms_audit_events: {
        Row: {
          action: string
          actor_member_id: string | null
          after_data: Json | null
          before_data: Json | null
          changed_keys: string[]
          created_at: string
          id: string
          metadata: Json
          target_id: string | null
          target_table: string
        }
        Insert: {
          action: string
          actor_member_id?: string | null
          after_data?: Json | null
          before_data?: Json | null
          changed_keys?: string[]
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_table: string
        }
        Update: {
          action?: string
          actor_member_id?: string | null
          after_data?: Json | null
          before_data?: Json | null
          changed_keys?: string[]
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_table?: string
        }
        Relationships: [
          {
            foreignKeyName: "cms_audit_events_actor_member_id_fkey"
            columns: ["actor_member_id"]
            isOneToOne: false
            referencedRelation: "members"
            referencedColumns: ["id"]
          },
        ]
      }
      entity_schemas: {
        Row: {
          active: boolean
          created_at: string
          description: string
          fields: Json
          id: string
          kind: string
          label: string
          relation_slots: string[]
          renderer_key: string | null
          schema_key: string
          table_name: string
          updated_at: string
          validation: Json
          version: number
        }
        Insert: {
          active?: boolean
          created_at?: string
          description?: string
          fields?: Json
          id?: string
          kind: string
          label: string
          relation_slots?: string[]
          renderer_key?: string | null
          schema_key: string
          table_name: string
          updated_at?: string
          validation?: Json
          version?: number
        }
        Update: {
          active?: boolean
          created_at?: string
          description?: string
          fields?: Json
          id?: string
          kind?: string
          label?: string
          relation_slots?: string[]
          renderer_key?: string | null
          schema_key?: string
          table_name?: string
          updated_at?: string
          validation?: Json
          version?: number
        }
        Relationships: []
      }
      entities: {
        Row: {
          created_at: string
          data: Json
          entity_type: string
          id: string
          owner_member_id: string | null
          published: boolean
          schema_id: string | null
          schema_key: string
          slug: string | null
          sort_at: string
          source_id: string | null
          source_table: string | null
          subtitle: string | null
          summary: string | null
          thumbnail_url: string | null
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          data?: Json
          entity_type: string
          id?: string
          owner_member_id?: string | null
          published?: boolean
          schema_id?: string | null
          schema_key?: string
          slug?: string | null
          sort_at?: string
          source_id?: string | null
          source_table?: string | null
          subtitle?: string | null
          summary?: string | null
          thumbnail_url?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          data?: Json
          entity_type?: string
          id?: string
          owner_member_id?: string | null
          published?: boolean
          schema_id?: string | null
          schema_key?: string
          slug?: string | null
          sort_at?: string
          source_id?: string | null
          source_table?: string | null
          subtitle?: string | null
          summary?: string | null
          thumbnail_url?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "entities_owner_member_id_fkey"
            columns: ["owner_member_id"]
            isOneToOne: false
            referencedRelation: "members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entities_schema_id_fkey"
            columns: ["schema_id"]
            isOneToOne: false
            referencedRelation: "entity_schemas"
            referencedColumns: ["id"]
          },
        ]
      }
      entity_relations: {
        Row: {
          created_at: string
          created_by_member_id: string | null
          from_entity_id: string
          id: string
          props: Json
          relation_type: string
          schema_id: string | null
          schema_key: string
          slot: string
          sort_order: number
          source_id: string | null
          source_table: string | null
          to_entity_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by_member_id?: string | null
          from_entity_id: string
          id?: string
          props?: Json
          relation_type: string
          schema_id?: string | null
          schema_key?: string
          slot?: string
          sort_order?: number
          source_id?: string | null
          source_table?: string | null
          to_entity_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by_member_id?: string | null
          from_entity_id?: string
          id?: string
          props?: Json
          relation_type?: string
          schema_id?: string | null
          schema_key?: string
          slot?: string
          sort_order?: number
          source_id?: string | null
          source_table?: string | null
          to_entity_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "entity_relations_created_by_member_id_fkey"
            columns: ["created_by_member_id"]
            isOneToOne: false
            referencedRelation: "members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entity_relations_from_entity_id_fkey"
            columns: ["from_entity_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entity_relations_schema_id_fkey"
            columns: ["schema_id"]
            isOneToOne: false
            referencedRelation: "entity_schemas"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entity_relations_to_entity_id_fkey"
            columns: ["to_entity_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
        ]
      }
      members: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          auth_user_id: string | null
          avatar_url: string | null
          bio: string | null
          created_at: string
          current_status: string | null
          email: string | null
          english_name: string | null
          id: string
          instrument: string | null
          name: string
          position: string | null
          role: Database["public"]["Enums"]["member_role"]
          status: Database["public"]["Enums"]["member_status"] | null
          student_year: number | null
          updated_at: string
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          auth_user_id?: string | null
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          current_status?: string | null
          email?: string | null
          english_name?: string | null
          id?: string
          instrument?: string | null
          name: string
          position?: string | null
          role?: Database["public"]["Enums"]["member_role"]
          status?: Database["public"]["Enums"]["member_status"] | null
          student_year?: number | null
          updated_at?: string
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          auth_user_id?: string | null
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          current_status?: string | null
          email?: string | null
          english_name?: string | null
          id?: string
          instrument?: string | null
          name?: string
          position?: string | null
          role?: Database["public"]["Enums"]["member_role"]
          status?: Database["public"]["Enums"]["member_status"] | null
          student_year?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "members_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "members"
            referencedColumns: ["id"]
          },
        ]
      }
      page_sections: {
        Row: {
          created_at: string
          id: string
          page_id: string
          props: Json
          section_id: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          page_id: string
          props?: Json
          section_id: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          page_id?: string
          props?: Json
          section_id?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "page_sections_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "page_sections_section_id_fkey"
            columns: ["section_id"]
            isOneToOne: false
            referencedRelation: "sections"
            referencedColumns: ["id"]
          },
        ]
      }
      pages: {
        Row: {
          created_at: string
          description: string | null
          id: string
          owner_member_id: string | null
          props: Json
          published: boolean
          slug: string
          subtitle: string | null
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          owner_member_id?: string | null
          props?: Json
          published?: boolean
          slug: string
          subtitle?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          owner_member_id?: string | null
          props?: Json
          published?: boolean
          slug?: string
          subtitle?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "pages_owner_member_id_fkey"
            columns: ["owner_member_id"]
            isOneToOne: false
            referencedRelation: "members"
            referencedColumns: ["id"]
          },
        ]
      }
      performances: {
        Row: {
          created_at: string
          event_date: string
          id: string
          notes: string | null
          poster_url: string | null
          published: boolean
          slug: string
          subtitle: string | null
          title: string
          type: Database["public"]["Enums"]["performance_type"]
          updated_at: string
          venue: string | null
        }
        Insert: {
          created_at?: string
          event_date: string
          id?: string
          notes?: string | null
          poster_url?: string | null
          published?: boolean
          slug: string
          subtitle?: string | null
          title: string
          type?: Database["public"]["Enums"]["performance_type"]
          updated_at?: string
          venue?: string | null
        }
        Update: {
          created_at?: string
          event_date?: string
          id?: string
          notes?: string | null
          poster_url?: string | null
          published?: boolean
          slug?: string
          subtitle?: string | null
          title?: string
          type?: Database["public"]["Enums"]["performance_type"]
          updated_at?: string
          venue?: string | null
        }
        Relationships: []
      }
      photos: {
        Row: {
          aspect: Database["public"]["Enums"]["photo_aspect"]
          caption: string | null
          category: Database["public"]["Enums"]["photo_category"]
          created_at: string
          display_order: number
          id: string
          performance_id: string | null
          published: boolean
          storage_path: string
          taken_at: string | null
          title: string
          updated_at: string
        }
        Insert: {
          aspect?: Database["public"]["Enums"]["photo_aspect"]
          caption?: string | null
          category?: Database["public"]["Enums"]["photo_category"]
          created_at?: string
          display_order?: number
          id?: string
          performance_id?: string | null
          published?: boolean
          storage_path: string
          taken_at?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          aspect?: Database["public"]["Enums"]["photo_aspect"]
          caption?: string | null
          category?: Database["public"]["Enums"]["photo_category"]
          created_at?: string
          display_order?: number
          id?: string
          performance_id?: string | null
          published?: boolean
          storage_path?: string
          taken_at?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "photos_performance_id_fkey"
            columns: ["performance_id"]
            isOneToOne: false
            referencedRelation: "performances"
            referencedColumns: ["id"]
          },
        ]
      }
      section_entities: {
        Row: {
          created_at: string
          entity_id: string
          id: string
          props: Json
          relation_type: string
          section_id: string
          slot: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          entity_id: string
          id?: string
          props?: Json
          relation_type?: string
          section_id: string
          slot?: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          entity_id?: string
          id?: string
          props?: Json
          relation_type?: string
          section_id?: string
          slot?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "section_entities_entity_id_fkey"
            columns: ["entity_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "section_entities_section_id_fkey"
            columns: ["section_id"]
            isOneToOne: false
            referencedRelation: "sections"
            referencedColumns: ["id"]
          },
        ]
      }
      sections: {
        Row: {
          created_at: string
          eyebrow: string | null
          id: string
          key: string
          owner_member_id: string | null
          props: Json
          published: boolean
          schema_key: string
          section_type: string
          subtitle: string | null
          title: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          eyebrow?: string | null
          id?: string
          key: string
          owner_member_id?: string | null
          props?: Json
          published?: boolean
          schema_key?: string
          section_type: string
          subtitle?: string | null
          title?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          eyebrow?: string | null
          id?: string
          key?: string
          owner_member_id?: string | null
          props?: Json
          published?: boolean
          schema_key?: string
          section_type?: string
          subtitle?: string | null
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sections_owner_member_id_fkey"
            columns: ["owner_member_id"]
            isOneToOne: false
            referencedRelation: "members"
            referencedColumns: ["id"]
          },
        ]
      }
      videos: {
        Row: {
          artist: string | null
          created_at: string
          display_order: number
          duration: string | null
          id: string
          is_highlight: boolean
          last_fetched_at: string | null
          performance_id: string | null
          published: boolean
          song: string | null
          team: string | null
          title: string
          updated_at: string
          views: number | null
          youtube_id: string
        }
        Insert: {
          artist?: string | null
          created_at?: string
          display_order?: number
          duration?: string | null
          id?: string
          is_highlight?: boolean
          last_fetched_at?: string | null
          performance_id?: string | null
          published?: boolean
          song?: string | null
          team?: string | null
          title: string
          updated_at?: string
          views?: number | null
          youtube_id: string
        }
        Update: {
          artist?: string | null
          created_at?: string
          display_order?: number
          duration?: string | null
          id?: string
          is_highlight?: boolean
          last_fetched_at?: string | null
          performance_id?: string | null
          published?: boolean
          song?: string | null
          team?: string | null
          title?: string
          updated_at?: string
          views?: number | null
          youtube_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "videos_performance_id_fkey"
            columns: ["performance_id"]
            isOneToOne: false
            referencedRelation: "performances"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      current_member_id: { Args: never; Returns: string }
      is_active_member: { Args: never; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
    }
    Enums: {
      member_role: "member" | "admin"
      member_status: "inactive" | "active" | "alumni"
      performance_type:
        | "regular"
        | "festival"
        | "special"
        | "stadium"
        | "welcome"
      photo_aspect: "portrait" | "landscape"
      photo_category:
        | "live"
        | "practice"
        | "studio"
        | "events"
        | "group"
        | "backstage"
    }
    CompositeTypes: { [_ in never]: never }
  }
}

export const Constants = {
  public: {
    Enums: {
      member_role: ["member", "admin"],
      member_status: ["inactive", "active", "alumni"],
      performance_type: [
        "regular",
        "festival",
        "special",
        "stadium",
        "welcome",
      ],
      photo_aspect: ["portrait", "landscape"],
      photo_category: [
        "live",
        "practice",
        "studio",
        "events",
        "group",
        "backstage",
      ],
    },
  },
} as const
